name: ROS buildfarm
description: Github Action to convert ROS packages to Debian packages
author: Jochen Sprickerhof
branding:
  icon: 'package'
  color: 'green'
inputs:
  ROS_DISTRO:
    description: The ROS distribution codename to compile for.
    required: true
  DEB_DISTRO:
    description: The Debian/Ubuntu distribution codename to compile for.
    required: true
  REPOS_FILE:
    description: Repos file with list of repositories to package.
    required: false
    default: sources.repos
  GITHUB_TOKEN:
    description: Set to deploy to a DEB_DISTRO-ROS_DISTRO branch in the same repo.
    required: false
    default: false
  SQUASH_HISTORY:
    description: If set to true, all previous commits on the target branch will be discarded.
    required: false
    default: false
  VERBOSE:
    description: Set to true to enable verbose builds.
    default: false
runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Cache ccache
      uses: pat-s/always-upload-cache@v3
      with:
        path: /home/runner/.cache/ccache
        key: ccache-${{ inputs.ROS_DISTRO }}-${{ github.sha }}-${{ github.run_id }}
        restore-keys: |
          ccache-${{ inputs.ROS_DISTRO }}-${{ github.sha }}
          ccache-${{ inputs.ROS_DISTRO }}
    - name: Setup build environment
      run: $GITHUB_ACTION_PATH/prepare.sh
      shell: sh
      env:
        DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
        REPOS_FILE: ${{ inputs.REPOS_FILE }}
    - name: Create packages
      run: $GITHUB_ACTION_PATH/build.sh
      shell: sh
      env:
        ROS_DISTRO: ${{ inputs.ROS_DISTRO }}
        DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
        VERBOSE: ${{ inputs.VERBOSE }}
    - name: Create apt repository
      run: $GITHUB_ACTION_PATH/repository.sh
      shell: sh
      env:
        ROS_DISTRO: ${{ inputs.ROS_DISTRO }}
        DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
    - name: Deploy
      if: ${{ inputs.GITHUB_TOKEN }}
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: ${{ inputs.DEB_DISTRO }}-${{ inputs.ROS_DISTRO }}
        FOLDER: /home/runner/apt_repo
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SQUASH_HISTORY: ${{ inputs.SQUASH_HISTORY }}
