#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause

while getopts cd:hr: OPTCHAR; do
  case "$OPTCHAR" in
    c)
      CONTINUE_PACKAGE_GENERATION=1
      ;;
    d)
      DEB_DISTRO="$OPTARG"
      ;;
    h)
      echo "usage: $0 [-c]"
      echo "  -c To continue at the last package and skip those already built."
      echo "  -d The Debian/Ubuntu distribution codename to compile for."
      echo "  -r The ROS distribution codename to compile for."
      exit
      ;;
    r)
      ROS_DISTRO="$OPTARG"
      ;;
    *)
      echo "Error parsing arguments"
      exit 1
      ;;
  esac
done
shift "$((OPTIND - 1))"

# make output directory
test -z "$CONTINUE_PACKAGE_GENERATION" && rm -rf apt_repo
mkdir -p apt_repo
APT_REPO="$(pwd)/apt_repo"

if [ -z "$DISTRIBUTION" ]; then
  if debian-distro-info --all | grep -q "$DEB_DISTRO"; then
    DISTRIBUTION=debian
  elif ubuntu-distro-info --all | grep -q "$DEB_DISTRO"; then
    DISTRIBUTION=ubuntu
  else
    echo "Unknown DEB_DISTRO: $DEB_DISTRO"
    exit 1
  fi
fi

case $ROS_DISTRO in
  debian)
    ;;
  boxturtle|cturtle|diamondback|electric|fuerte|groovy|hydro|indigo|jade|kinetic|lunar)
    echo "Unsupported ROS 1 version: $ROS_DISTRO"
    exit 1
    ;;
  melodic|noetic)
    BLOOM=ros
    ROS_DEB="$ROS_DISTRO-"
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o "$APT_REPO/ros-archive-keyring.gpg"
    set -- --extra-repository="deb http://packages.ros.org/ros/ubuntu $DEB_DISTRO main" --extra-repository-key="$APT_REPO/ros-archive-keyring.gpg" "$@"
    ;;
  *)
    # assume ROS 2 so we don't have to list versions
    BLOOM=ros
    ROS_DEB="$ROS_DISTRO-"
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o "$APT_REPO/ros-archive-keyring.gpg"
    set -- --extra-repository="deb http://packages.ros.org/ros2/ubuntu $DEB_DISTRO main" --extra-repository-key="$APT_REPO/ros-archive-keyring.gpg" "$@"
    ;;
esac

echo "Add unreleased packages to rosdep"

set -ex

for PKG in $(catkin_topological_order --only-names); do
  printf "%s:\n  %s:\n  - %s\n" "$PKG" "$DISTRIBUTION" "ros-$ROS_DEB$(printf '%s' "$PKG" | tr '_' '-')" >> "$APT_REPO/local.yaml"
done
echo "yaml file://$APT_REPO/local.yaml $ROS_DISTRO" > "$APT_REPO/1-local.list"
echo "$ROSDEP_SOURCE" > "$APT_REPO/2-remote.list"

ROSDEP_SOURCE_PATH="$APT_REPO:/etc/ros/rosdep/sources.list.d/" rosdep update

echo "Run sbuild"

# Don't build tests
export DEB_BUILD_OPTIONS=nocheck

TOTAL="$(catkin_topological_order --only-names | wc -l)"
COUNT=1

# TODO: use colcon list -tp in future
for PKG_PATH in $(catkin_topological_order --only-folders); do
  echo "::group::Building $COUNT/$TOTAL: $PKG_PATH"
  test -f "$PKG_PATH/CATKIN_IGNORE" && echo "Skipped" && continue
  test -f "$PKG_PATH/COLCON_IGNORE" && echo "Skipped" && continue
  (
  cd "$PKG_PATH"
  GENERATED_DEBIAN_PACKAGE="ros-${ROS_DEB}$(catkin_topological_order --only-names | tr '_' '-')"
  if [ -n "$CONTINUE_PACKAGE_GENERATION" ] && ls "$APT_REPO/${GENERATED_DEBIAN_PACKAGE}_"*.deb >/dev/null 2>&1; then
    echo " Skipping already generated package: ${GENERATED_DEBIAN_PACKAGE}"
    exit
  fi

  bloom-generate "${BLOOM}debian" --os-name="$DISTRIBUTION" --os-version="$DEB_DISTRO" --ros-distro="$ROS_DISTRO"

  # Set the version based on the checked out tag that contain at least on digit
  # strip any leading non digits as they are not part of the version number
  sed -i "1 s@([^)]*)@($( (git describe --tag  --match "*[0-9]*" 2>/dev/null || echo 0) | sed 's@^[^0-9]*@@')-$(date +%Y.%m.%d.%H.%M))@" debian/changelog

  # https://github.com/ros-infrastructure/bloom/pull/643
  echo 11 > debian/compat

  # dpkg-source-opts: no need for upstream.tar.gz
  sbuild --chroot-mode=unshare --no-clean-source --no-run-lintian \
    --dpkg-source-opts="-Zgzip -z1 --format=1.0 -sn" --build-dir="$APT_REPO" \
    --extra-package="$APT_REPO" "$@"

  rm -f debian/rules debian/compat debian/changelog debian/control debian/copyright debian/source/format debian/source/options
  rmdir -p debian/source || true

  )
  COUNT=$((COUNT+1))
  echo "::endgroup::"
done

# revert rosdep cache
rosdep update

ccache -sv
