#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause

# defaults
. /etc/os-release
DEB_DISTRO="${DEB_DISTRO:-$VERSION_CODENAME}"
DEB_ARCH="${DEB_ARCH:-$(dpkg --print-architecture)}"

while getopts a:d:hr: OPTCHAR; do
  case "$OPTCHAR" in
    a)
      DEB_ARCH="$OPTCHAR"
      ;;
    d)
      DEB_DISTRO="$OPTARG"
      ;;
    h)
      echo "usage: $0 [-a] [-d] [-r]"
      echo "  -a The architecture to compile for."
      echo "  -d The Debian/Ubuntu distribution codename to compile for."
      echo "  -r The ROS distribution codename to compile for."
      exit
      ;;
    r)
      ROS_DISTRO="$OPTARG"
      ;;
    *)
      echo "Error parsing arguments"
      exit 1
      ;;
  esac
done
shift "$((OPTIND - 1))"

set -ex

test -d src && vcs export src --exact-with-tags > apt_repo/sources.repos

cd apt_repo

apt-ftparchive packages . > Packages
apt-ftparchive release . > Release

REPOSITORY="$(printf "%s" "$GITHUB_REPOSITORY" | tr / _)"
BRANCH="${PACKAGES_BRANCH:-$DEB_DISTRO-$ROS_DISTRO-$DEB_ARCH}"
echo '```bash' > README.md

if [ "$GITHUB_SERVER_URL" = "https://github.com" ]; then
  echo "echo \"deb [trusted=yes] https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$BRANCH/ ./\" | sudo tee /etc/apt/sources.list.d/$REPOSITORY-$BRANCH.list" >> README.md
else
  echo "echo \"deb [trusted=yes] $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/raw/$BRANCH/ ./\" | sudo tee /etc/apt/sources.list.d/$REPOSITORY-$BRANCH.list" >> README.md
fi

echo "echo \"yaml $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/raw/$BRANCH/local.yaml $ROS_DISTRO\" | sudo tee /etc/ros/rosdep/sources.list.d/1-$REPOSITORY-$BRANCH.list" >> README.md
echo '```' >> README.md

test -z "$GITHUB_TOKEN" && exit

git init -b "$BRANCH"

test -n "$GIT_LFS" && git lfs track "*.deb" "*.ddeb"

git remote add origin "$(echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" | sed "s#https://#https://x-access-token:${GITHUB_TOKEN}@#")"
if [ -z "$SQUASH_HISTORY" ]; then
  git fetch origin "$BRANCH" || true
  git reset --soft FETCH_HEAD || true
fi
git add .
git -c user.name=Github -c user.email=none commit --message="Generated from $(git -C ../repo rev-parse --short HEAD)"
git push --force origin "$BRANCH"
